Version 0.16-SNAPSHOT & update used wemi

diff --git a/wemi b/wemi
--- a/wemi
+++ b/wemi
@@ -40,7 +40,7 @@
 #			--print-java-exe	- Print path to java executable that would be used and exit
 #			--print-wemi-home	- Print path to directory with Wemi jars and exit
 
-readonly wemi_version='0.15-SNAPSHOT'
+readonly wemi_version='0.15'
 readonly java_min_version='8'
 
 log() { echo "$@" 1>&2; }
@@ -125,7 +125,11 @@ download_to_file() {
 	if command_exists curl; then
 		curl -C - --fail --retry 3 --location --output "$2" --url "$1" || fail "Failed to fetch $1 to $2 (curl: $?)"
 	elif command_exists wget; then
-		wget --tries=3 --continue --show-progress --output-document="$2" "$1" || fail "Failed to fetch $1 to $2 (wget: $?)"
+		# Download resume in wget is not supported, because it does not play well with custom output file
+		if [ -e "$2" ]; then
+			rm "$2" || log "Failed to delete old download file $2 (rm: $?)"
+		fi
+		wget --show-progress --output-document="$2" "$1" || fail "Failed to fetch $1 to $2 (wget: $?)"
 	else
 		fail_unsatisfied "curl or wget"
 	fi
@@ -137,7 +141,7 @@ download_to_output() {
 	if command_exists curl; then
 		curl --fail --retry 3 --location --silent --show-error --url "$1" || fail "Failed to fetch $1 (curl: $?)"
 	elif command_exists wget; then
-		wget --tries=3 --quiet --output-document=- "$1" || fail "Failed to fetch $1 (wget: $?)"
+		wget --quiet --output-document=- "$1" || fail "Failed to fetch $1 (wget: $?)"
 	else
 		fail_unsatisfied "curl or wget"
 	fi
@@ -507,7 +511,7 @@ fetch_wemi() {
 
 	# List of mirrors in order of preference
 	wemi_url_darkyen_="https://darkyen.com/wemi/${wemi_version}/wemi.tar.gz"
-	wemi_url_github_="https://github.com/Darkyenus/wemi/releases/download/v${wemi_version}/wemi.tar.gz"
+	wemi_url_github_="https://github.com/Darkyenus/wemi/releases/download/${wemi_version}/wemi.tar.gz"
 
 	redownload_='false'
 	if [ "${wemi_version%-SNAPSHOT}" != "${wemi_version}" ]; then
